import uuid
from datetime import datetime
from sqlalchemy import String, Integer, Float, DateTime, Text, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID, JSONB
from app.database import Base


class Recommendation(Base):
    """A single job recommendation for a user, generated by the recommendation agent."""

    __tablename__ = "recommendations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("jobs.id", ondelete="CASCADE"), index=True
    )

    # Scoring
    match_score: Mapped[float] = mapped_column(Float, nullable=False)  # 0.0 – 1.0
    rank: Mapped[int] = mapped_column(Integer)

    # Detailed score breakdown (JSON snapshot for reproducibility)
    score_breakdown: Mapped[dict | None] = mapped_column(JSONB)
    # {
    #   "semantic_similarity": 0.92,
    #   "skill_overlap": 0.85,
    #   "location_fit": 1.0,
    #   "salary_fit": 0.75,
    #   "experience_fit": 1.0,
    #   "job_type_fit": 1.0,
    #   "matching_skills": ["python", "django"],
    #   "missing_skills": ["kubernetes"]
    # }

    # Retrieval context
    retrieval_method: Mapped[str | None] = mapped_column(String(50))  # semantic/hybrid/lexical
    candidate_pool_position: Mapped[int | None] = mapped_column(Integer)  # Position in candidate pool before ranking

    # RAG explanation
    explanation: Mapped[str | None] = mapped_column(Text)

    # Audit trail
    recommendation_run_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("recommendation_runs.id", ondelete="SET NULL")
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    # Relationships
    user: Mapped["User"] = relationship(back_populates="recommendations")  # noqa: F821
    job: Mapped["Job"] = relationship()  # noqa: F821
    recommendation_run: Mapped["RecommendationRun | None"] = relationship(  # noqa: F821
        back_populates="recommendations"
    )


class SavedJob(Base):
    """A job saved/bookmarked by a user."""

    __tablename__ = "saved_jobs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("jobs.id", ondelete="CASCADE"), index=True
    )
    saved_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    user: Mapped["User"] = relationship(back_populates="saved_jobs")  # noqa: F821
    job: Mapped["Job"] = relationship()  # noqa: F821
